Move import of BeautfulSoup to avoid import err...
Move import of BeautfulSoup to avoid import error.
Close temporary file and delete VideoWriter instance to allow temp file
to be deleted in Windows.  Otherwise, Windows will report an error
like:

    WindowsError: [Error 32] The process cannot access the file because
        it is being used by another process: ...